* Check for vala 0.1.7 instead of 0.1.6 in configure.acr * Fix history cursor position for dietline * Using dietline with ':' visual mode key':' command.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -191,7 +191,7 @@ case $flag in
 echo "PKGNAME:   radare"
 echo "VERSION:   0.9.4"
 echo "LANGS:     c"
-echo "REQUIRED:  libdl lib>=vala-1.0 libvala-1.0>=0.1.6"
+echo "REQUIRED:  libdl lib>=vala-1.0 libvala-1.0>=0.1.7"
 echo "OPTIONAL:  libewf"
 echo "PKG-CONFIG:  gtk+-2.0 vte"
 echo "FLAGS:     --without-readline --without-usb-sniffer --without-debugger --with-java --with-wii --enable-w32 --with-sysproxy --without-vala --without-gui"
@@ -259,7 +259,7 @@ parse_options $1
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_DL DL_LIBS SOLARIS DARWIN SHARED_EXT SHARED_CFLAGS WINDOWS READLINE HAVE_RL_COMPLETION_MATCHES RADARE_LDFLAGS HAVE_LIB_READLINE HAVE_USB_H USBSNF DEBUGGER JAVA WII W32 SYSPROXY VALA HAVE_VALAC VALAC HAVE_VALA_1_0_VERSION_0_1_6 WITH_VALA _CFLAGS SIZEOF_OFF_T HAVE_LIB_EWF GUI HAVE_GTKDIALOG GTKDIALOG GTK_FLAGS GTK_LIBS HAVE_PKGCFG_GTK_2_0 VTE_FLAGS VTE_LIBS HAVE_PKGCFG_VTE HAVE_VALA"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_DL DL_LIBS SOLARIS DARWIN SHARED_EXT SHARED_CFLAGS WINDOWS READLINE HAVE_RL_COMPLETION_MATCHES RADARE_LDFLAGS HAVE_LIB_READLINE HAVE_USB_H USBSNF DEBUGGER JAVA WII W32 SYSPROXY VALA HAVE_VALAC VALAC HAVE_VALA_1_0_VERSION_0_1_7 WITH_VALA _CFLAGS SIZEOF_OFF_T HAVE_LIB_EWF GUI HAVE_GTKDIALOG GTKDIALOG GTK_FLAGS GTK_LIBS HAVE_PKGCFG_GTK_2_0 VTE_FLAGS VTE_LIBS HAVE_PKGCFG_VTE HAVE_VALA"
 
 create_environ
 
@@ -402,13 +402,13 @@ else
  HAVE_VALAC=0
  VALAC=valac
  echo no ; fi
-HAVE_VALA_1_0_VERSION_0_1_6=0
-printf "checking version of library vala-1.0 >= 0.1.6... "
-pkg-config --atleast-version=0.1.6 vala-1.0 >/dev/null 2>&1
-if [ $? = 0 ]; then HAVE_VALA_1_0_VERSION_0_1_6=1 ; echo ok; else
+HAVE_VALA_1_0_VERSION_0_1_7=0
+printf "checking version of library vala-1.0 >= 0.1.7... "
+pkg-config --atleast-version=0.1.7 vala-1.0 >/dev/null 2>&1
+if [ $? = 0 ]; then HAVE_VALA_1_0_VERSION_0_1_7=1 ; echo ok; else
 echo "no" ; fi
-if [ "$HAVE_VALA_1_0_VERSION_0_1_6" = "0" ]; then
-echo "   Needs vala 0.1.6 at least" >&2 
+if [ "$HAVE_VALA_1_0_VERSION_0_1_7" = "0" ]; then
+echo "   Needs vala 0.1.7 at least" >&2 
 export VALAC=""; fi
 if [ "$VALAC" = "valac" ]; then
 export WITH_VALA="0"
