* Ooops. we need valac 0.3.2! (current svn) * Fix broken build

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -193,7 +193,7 @@ case $flag in
 echo "PKGNAME:   radare"
 echo "VERSION:   0.9.6"
 echo "LANGS:     c"
-echo "REQUIRED:  libdl lib>=vala-1.0 libvala-1.0>=0.3.1"
+echo "REQUIRED:  libdl lib>=vala-1.0 libvala-1.0>=0.3.2"
 echo "OPTIONAL:  libewf"
 echo "PKG-CONFIG:  gtk+-2.0 vte"
 echo "FLAGS:     --without-readline --without-usb-sniffer --without-debugger --with-java --with-wii --enable-w32 --with-sysproxy --without-vala --with-maemo --without-gui"
@@ -262,7 +262,7 @@ parse_options $1
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_DL DL_LIBS SOLARIS DARWIN SHARED_EXT SHARED_CFLAGS WINDOWS READLINE HAVE_RL_COMPLETION_MATCHES RADARE_LDFLAGS HAVE_LIB_READLINE HAVE_USB_H USBSNF DEBUGGER JAVA WII W32 SYSPROXY VALA HAVE_VALAC VALAC HAVE_VALA_1_0_VERSION_0_3_1 GUI WITH_VALA _CFLAGS SIZEOF_OFF_T HAVE_LIB_EWF MAEMO HAVE_GTKDIALOG GTKDIALOG GTK_FLAGS GTK_LIBS HAVE_PKGCFG_GTK_2_0 VTE_FLAGS VTE_LIBS HAVE_PKGCFG_VTE HAVE_VALA"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_DL DL_LIBS SOLARIS DARWIN SHARED_EXT SHARED_CFLAGS WINDOWS READLINE HAVE_RL_COMPLETION_MATCHES RADARE_LDFLAGS HAVE_LIB_READLINE HAVE_USB_H USBSNF DEBUGGER JAVA WII W32 SYSPROXY VALA HAVE_VALAC VALAC HAVE_VALA_1_0_VERSION_0_3_2 GUI WITH_VALA _CFLAGS SIZEOF_OFF_T HAVE_LIB_EWF MAEMO HAVE_GTKDIALOG GTKDIALOG GTK_FLAGS GTK_LIBS HAVE_PKGCFG_GTK_2_0 VTE_FLAGS VTE_LIBS HAVE_PKGCFG_VTE HAVE_VALA"
 
 create_environ
 
@@ -405,13 +405,13 @@ else
  HAVE_VALAC=0
  VALAC=valac
  echo no ; fi
-HAVE_VALA_1_0_VERSION_0_3_1=0
-printf "checking version of library vala-1.0 >= 0.3.1... "
-pkg-config --atleast-version=0.3.1 vala-1.0 >/dev/null 2>&1
-if [ $? = 0 ]; then HAVE_VALA_1_0_VERSION_0_3_1=1 ; echo ok; else
+HAVE_VALA_1_0_VERSION_0_3_2=0
+printf "checking version of library vala-1.0 >= 0.3.2... "
+pkg-config --atleast-version=0.3.2 vala-1.0 >/dev/null 2>&1
+if [ $? = 0 ]; then HAVE_VALA_1_0_VERSION_0_3_2=1 ; echo ok; else
 echo "no" ; fi
-if [ "$HAVE_VALA_1_0_VERSION_0_3_1" = "0" ]; then
-echo "   Needs vala 0.3.1 at least" >&2 
+if [ "$HAVE_VALA_1_0_VERSION_0_3_2" = "0" ]; then
+echo "   Needs vala 0.3.2 at least" >&2 
 export VALAC=""
 export VALA="0"
 export GUI="0"; fi
