* radare 0.9.6 released!   - We need at least valac 0.3.3 (svn one)   - Fix warning from configure.acr script   - Update changelog for the release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -141,26 +141,31 @@ System types:
   --target=TARGET        configure for building compilers for TARGET [HOST]
 EOF2
 
-printf "\nOptional Features:
+printf "
+Optional Features:
   --without-readline     disables the readline support 
   --without-usb-sniffer  disables the build of the libusb sniffer 
   --without-debugger     disables the debugger layer 
   --with-java            builds the java api 
   --with-wii             builds the wii plugin for usbgecko 
-  --enable-w32           enables the build of w32 version of the framework (mingw32) 
+  --enable-w32           enables the build of w32 version using mingw32 
   --with-sysproxy        builds the syscall proxy plugin 
   --without-vala         disables the build of all the vala-dependant parts 
   --with-maemo           build hildon interface 
-  --without-gui          radare without the gtk frontend \n"
-printf "\nSome influential environment variables:
+  --without-gui          radare without the gtk frontend 
+"
+printf "
+Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
               headers in a nonstandard directory <include dir>
-  CPP         C preprocessor\n"
-printf "\nReport bugs to: pancake <pancake@youterm.com>"
+  CPP         C preprocessor
+"
+printf "
+Report bugs to: pancake <pancake@youterm.com>"
 echo ""
 exit 0
 }
@@ -193,7 +198,7 @@ case $flag in
 echo "PKGNAME:   radare"
 echo "VERSION:   0.9.6"
 echo "LANGS:     c"
-echo "REQUIRED:  libdl lib>=vala-1.0 libvala-1.0>=0.3.2"
+echo "REQUIRED:  libdl lib>=vala-1.0 libvala-1.0>=0.3.3"
 echo "OPTIONAL:  libewf"
 echo "PKG-CONFIG:  gtk+-2.0 vte"
 echo "FLAGS:     --without-readline --without-usb-sniffer --without-debugger --with-java --with-wii --enable-w32 --with-sysproxy --without-vala --with-maemo --without-gui"
@@ -262,7 +267,7 @@ parse_options $1
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_DL DL_LIBS SOLARIS DARWIN SHARED_EXT SHARED_CFLAGS WINDOWS READLINE HAVE_RL_COMPLETION_MATCHES RADARE_LDFLAGS HAVE_LIB_READLINE HAVE_USB_H USBSNF DEBUGGER JAVA WII W32 SYSPROXY VALA HAVE_VALAC VALAC HAVE_VALA_1_0_VERSION_0_3_2 GUI WITH_VALA _CFLAGS SIZEOF_OFF_T HAVE_LIB_EWF MAEMO HAVE_GTKDIALOG GTKDIALOG GTK_FLAGS GTK_LIBS HAVE_PKGCFG_GTK_2_0 VTE_FLAGS VTE_LIBS HAVE_PKGCFG_VTE HAVE_VALA"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS LDFLAGS HAVE_LANG_C LIL_ENDIAN BIG_ENDIAN BYTEORDER HAVE_LIB_DL DL_LIBS SOLARIS DARWIN SHARED_EXT SHARED_CFLAGS WINDOWS READLINE HAVE_RL_COMPLETION_MATCHES RADARE_LDFLAGS HAVE_LIB_READLINE HAVE_USB_H USBSNF DEBUGGER JAVA WII W32 SYSPROXY VALA HAVE_VALAC VALAC HAVE_VALA_1_0_VERSION_0_3_3 GUI WITH_VALA _CFLAGS SIZEOF_OFF_T HAVE_LIB_EWF MAEMO HAVE_GTKDIALOG GTKDIALOG GTK_FLAGS GTK_LIBS HAVE_PKGCFG_GTK_2_0 VTE_FLAGS VTE_LIBS HAVE_PKGCFG_VTE HAVE_VALA"
 
 create_environ
 
@@ -405,13 +410,13 @@ else
  HAVE_VALAC=0
  VALAC=valac
  echo no ; fi
-HAVE_VALA_1_0_VERSION_0_3_2=0
-printf "checking version of library vala-1.0 >= 0.3.2... "
-pkg-config --atleast-version=0.3.2 vala-1.0 >/dev/null 2>&1
-if [ $? = 0 ]; then HAVE_VALA_1_0_VERSION_0_3_2=1 ; echo ok; else
+HAVE_VALA_1_0_VERSION_0_3_3=0
+printf "checking version of library vala-1.0 >= 0.3.3... "
+pkg-config --atleast-version=0.3.3 vala-1.0 >/dev/null 2>&1
+if [ $? = 0 ]; then HAVE_VALA_1_0_VERSION_0_3_3=1 ; echo ok; else
 echo "no" ; fi
-if [ "$HAVE_VALA_1_0_VERSION_0_3_2" = "0" ]; then
-echo "   Needs vala 0.3.2 at least" >&2 
+if [ "$HAVE_VALA_1_0_VERSION_0_3_3" = "0" ]; then
+echo "   Needs vala 0.3.3 at least" >&2 
 export VALAC=""
 export VALA="0"
 export GUI="0"; fi
